// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package srcgo

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type EgressLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      struct {
		_    structs.HostLayout
		In6U struct {
			_       structs.HostLayout
			U6Addr8 [16]uint8
		}
	}
}

type EgressPathMapEntry struct {
	_      structs.HostLayout
	Header struct {
		_          structs.HostLayout
		VerQosFlow uint32
		Next       uint8
		Len        uint8
		Payload    uint16
		Type       uint8
		Haddr      uint8
		Rsv        uint16
		Dst        struct {
			_   structs.HostLayout
			Dst uint64
		}
		Src struct {
			_   structs.HostLayout
			Src uint64
		}
	}
	Path       [255]uint32
	PathLen    uint8
	RouterAddr [16]uint8
	_          [1]byte
	RouterPort uint16
}

// LoadEgress returns the embedded CollectionSpec for Egress.
func LoadEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Egress: %w", err)
	}

	return spec, err
}

// LoadEgressObjects loads Egress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*EgressObjects
//	*EgressPrograms
//	*EgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// EgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EgressSpecs struct {
	EgressProgramSpecs
	EgressMapSpecs
	EgressVariableSpecs
}

// EgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EgressProgramSpecs struct {
	ScionEgress *ebpf.ProgramSpec `ebpf:"scion_egress"`
}

// EgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EgressMapSpecs struct {
	Ipv6ToScion *ebpf.MapSpec `ebpf:"ipv6_to_scion"`
	PathMap     *ebpf.MapSpec `ebpf:"path_map"`
	PathReq     *ebpf.MapSpec `ebpf:"path_req"`
}

// EgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EgressVariableSpecs struct {
}

// EgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type EgressObjects struct {
	EgressPrograms
	EgressMaps
	EgressVariables
}

func (o *EgressObjects) Close() error {
	return _EgressClose(
		&o.EgressPrograms,
		&o.EgressMaps,
	)
}

// EgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type EgressMaps struct {
	Ipv6ToScion *ebpf.Map `ebpf:"ipv6_to_scion"`
	PathMap     *ebpf.Map `ebpf:"path_map"`
	PathReq     *ebpf.Map `ebpf:"path_req"`
}

func (m *EgressMaps) Close() error {
	return _EgressClose(
		m.Ipv6ToScion,
		m.PathMap,
		m.PathReq,
	)
}

// EgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type EgressVariables struct {
}

// EgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type EgressPrograms struct {
	ScionEgress *ebpf.Program `ebpf:"scion_egress"`
}

func (p *EgressPrograms) Close() error {
	return _EgressClose(
		p.ScionEgress,
	)
}

func _EgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed egress_bpfel.o
var _EgressBytes []byte
